### ISSUE TITLE
[REQUEST] Ability to execute commands after a player win and loss

### ISSUE THREAD

**Issue by DuckMC** [TroDerp/EggWars#35]
**Description:** Ability to execute commands after a player win and loss

It would be a nice addition that you could set commands to be executed after someone wins or loses a game.

An example/suggestion of how it might look in the config:
```
rewards:
    winner:
    - points give %player% 1
    - level addExp 100 %player%
    losers:
    - level addExp 50 %player%
```
